services:
  zeroclaw:
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "42617"   # gateway
    volumes:
      - zeroclaw-data:/zeroclaw-data
    environment:
      ZEROCLAW_ALLOW_PUBLIC_BIND: "1"
      MODEL_API_KEY: "${MODEL_API_KEY}"

volumes:
  zeroclaw-data: